# fly.toml app configuration file generated for labels on 2023-06-12T16:07:23+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "labels"
primary_region = "lhr"
kill_signal = "SIGTERM"
kill_timeout = "5s"

[experimental]
  auto_rollback = true

[deploy]
  release_command = "/app/bin/migrate"

[env]
  PHX_HOST = "labels.fly.dev"
  PORT = "8080"

[[services]]
  protocol = "tcp"
  internal_port = 8080
  processes = ["app"]
  # https://fly.io/docs/apps/autostart-stop/
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

  [[services.ports]]
    port = 80
    handlers = ["http"]

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "1s"
    restart_limit = 0
